name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building application"


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: echo "Running tests"


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying application"

# job dependencies:
#   test:
#     needs: build

# we will write it like this to ensure that the test job only runs after the build job has completed successfully. This way, we can maintain a proper CI/CD pipeline where the build must pass before any tests are executed.